// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC-YzGFVr-6W1XXdpN7bT9-7cAp9ZMRvg',
    appId: '1:126829732932:web:bec780ed53ff1ce88b8811',
    messagingSenderId: '126829732932',
    projectId: 'utibu-health-app-9d583',
    authDomain: 'utibu-health-app-9d583.firebaseapp.com',
    storageBucket: 'utibu-health-app-9d583.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9_eaRzg2mooPmEnOazvDZOUUHuybtOsU',
    appId: '1:126829732932:android:a7b8bcd85614b8e68b8811',
    messagingSenderId: '126829732932',
    projectId: 'utibu-health-app-9d583',
    storageBucket: 'utibu-health-app-9d583.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBole2o9YlBSXDd5F16MbpSOwjuuo_0TJQ',
    appId: '1:126829732932:ios:ae478410cf0bc8118b8811',
    messagingSenderId: '126829732932',
    projectId: 'utibu-health-app-9d583',
    storageBucket: 'utibu-health-app-9d583.appspot.com',
    iosBundleId: 'com.example.utibuHealthApp',
  );
}
